In [8]:
densities = " ░▒▓█"

In [ ]:
import cv2
import numpy as np

# Load the image
image_path = 'images/monalisa.jpg'
image = cv2.imread(image_path)

# Convert the image to grayscale
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# The grayscale image is now a matrix of intensity values
intensity_matrix = np.array(gray_image)

# Print the intensity matrix
print(intensity_matrix)

[[114  87  86 ... 127 109  87]
 [115 123 115 ...  79  83  91]
 [103 110  80 ...  83  64  40]
 ...
 [119  79  79 ... 147  95  42]
 [143  55  69 ...  23  42  16]
 [105  60  52 ...  64  53 135]]


In [6]:
print(intensity_matrix.shape)
print(intensity_matrix.max())

(1192, 800)
246


In [16]:
intensity_matrix = intensity_matrix / (intensity_matrix.max() / (len(densities) -1))
intensity_matrix = intensity_matrix.astype(int)
print(intensity_matrix.max())
print(intensity_matrix)

4
[[1 0 0 ... 1 1 0]
 [1 1 1 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [1 0 0 ... 1 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 1]]


In [19]:
with open('images/monalisa.txt', 'w', encoding='utf-8') as f:
    for row in intensity_matrix:
        for intensity in row:
            f.write(densities[intensity])
        f.write('\n')
